/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.9.1.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as getItemById from "../getItemById";
import type * as getItemsByType from "../getItemsByType";
import type * as getItemsByTypeSort from "../getItemsByTypeSort";
import type * as getPurchaseByUserId from "../getPurchaseByUserId";
import type * as http from "../http";
import type * as insertItem from "../insertItem";
import type * as insertPurchase from "../insertPurchase";
import type * as postItem from "../postItem";
import type * as postPurchase from "../postPurchase";
import type * as queryItem from "../queryItem";
import type * as queryPurchase from "../queryPurchase";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  getItemById: typeof getItemById;
  getItemsByType: typeof getItemsByType;
  getItemsByTypeSort: typeof getItemsByTypeSort;
  getPurchaseByUserId: typeof getPurchaseByUserId;
  http: typeof http;
  insertItem: typeof insertItem;
  insertPurchase: typeof insertPurchase;
  postItem: typeof postItem;
  postPurchase: typeof postPurchase;
  queryItem: typeof queryItem;
  queryPurchase: typeof queryPurchase;
}>;
